export default [
  {
    color: '#29C477',
    description: '测试执行通过',
    name: '通过',
    key: 'PASSED',
    final: true,
    native: true,
    readOnly: true,
    type: 'PASSED',
  },
  {
    color: '#3683FF',
    description: '测试执行待执行',
    name: '待执行',
    key: 'TODO',
    final: false,
    native: true,
    readOnly: true,
    type: 'TODO',
  },
  {
    color: '#FFBF36',
    description: '测试执行正在执行中',
    name: '正在执行',
    key: 'EXECUTING',
    final: false,
    native: true,
    readOnly: true,
    type: 'EXECUTING',
  },
  {
    color: '#FF7236',
    description: '测试执行失败',
    final: true,
    name: '失败',
    key: 'FAILED',
    native: true,
    readOnly: true,
    type: 'FAILED',
  },
  {
    color: '#846BFF',
    description: '测试执行阻塞',
    final: false,
    name: '阻塞',
    key: 'BLOCK',
    native: true,
    readOnly: true,
    type: 'BLOCK',
  },
  {
    color: '#B5BAC5',
    description: '测试执行已取消',
    final: false,
    name: '已取消',
    key: 'CANCEL',
    native: true,
    readOnly: true,
    type: 'CANCEL',
  },
];
