export default [
  {
    color: '#36B37E',
    description: '测试执行通过',
    name: '通过',
    key: 'PASSED',
    final: true,
    native: true,
    readOnly: true,
    type: 'PASSED',
  },
  {
    color: '#4B8BFF',
    description: '测试执行待执行',
    name: '待执行',
    key: 'TODO',
    final: false,
    native: true,
    readOnly: true,
    type: 'TODO',
  },
  {
    color: '#FFAB00',
    description: '测试执行正在执行中',
    name: '正在执行',
    key: 'EXECUTING',
    final: false,
    native: true,
    readOnly: true,
    type: 'EXECUTING',
  },
  {
    color: '#FF7452',
    description: '测试执行失败',
    final: true,
    name: '失败',
    key: 'FAILED',
    native: true,
    readOnly: true,
    type: 'FAILED',
  },
];
